Repository nyu-devops-fall19-suppliers/suppliers, pull requests merged in 2019-11, with the labels that each got.

#104 Add Travis CI to the repo
  .travis.yml
  README.md
Labels: technical debt

#105 Add Codecov badge to repo
  README.md
Labels: technical debt

#110 Update .travis.yml
  .travis.yml
Labels: technical debt

#121 Behavior Driven Development Setup
  features/steps/supplier_steps.py
  features/suppliers.feature
  requirements.txt
Labels: enhancement

#127 Migrate local database to the cloud
  Vagrantfile
  requirements.txt
  service/models.py
  tests/test_service.py
  tests/test_suppliers.py
Labels: enhancement, technical debt

#128 Builds a simple UI for supplier service.
  service/service.py
  service/static/css/blue_bootstrap.min.css
  service/static/css/darkly_bootstrap.min.css
  service/static/css/flatly_bootstrap.min.css
  service/static/css/slate_bootstrap.min.css
  service/static/images/newapp-icon.png
  service/static/index.html
  service/static/js/jquery-3.1.1.min.js
  service/static/js/rest_api.js
  tests/test_service.py
Labels: enhancement

#131 Add IBM Cloud manifest.yml
  manifest.yml
Labels: technical debt

#135 Fix bugs for IBM Cloud pipeline tests
  tests/test_service.py
Labels: bug, testing

#139 Fix Server Address in environment.py
  features/environment.py
Labels: bug

#136 Fix bugs in IBM Cloud deploy pipeline
  requirements.txt
Labels: bug

#144 BDD test for Query by averageRating.
  features/suppliers.feature
Labels: enhancement

#146 BDD test for Query by averageRating.
  features/suppliers.feature
Labels: enhancement
