Repository nyu-devops-fall19-suppliers/suppliers, pull requests merged in 2019-10, with the labels that each got.

#41 Set up MongoDB environment
  .gitignore
  Vagrantfile
  requirements.txt
  tests/__init__.pyc
  ubuntu-bionic-18.04-cloudimg-console.log
Labels: technical debt

#48 Add List Operation Route
  flask-supplier/service.py
Labels: enhancement

#50 Added Flask-MongoEngine to requirements.txt
  requirements.txt
Labels: enhancement

#51 Implemented a models.py file which holds the data schema of the database
  flask-supplier/models.py
Labels: enhancement

#53 basic methods implementations and testing bug fix
  .coverage
  requirements.txt
  service/__init__.py
  service/__pycache__/__init__.cpython-36.pyc
  service/__pycache__/models.cpython-36.pyc
  service/__pycache__/service.cpython-36.pyc
  service/models.py
  service/service.py
  tests/__pycache__/__init__.cpython-36.pyc
  tests/__pycache__/suppliers_factory.cpython-36.pyc
  tests/__pycache__/test_service.cpython-36.pyc
  tests/__pycache__/test_suppliers.cpython-36.pyc
  tests/suppliers_factory.py
  tests/test_service.py
  tests/test_suppliers.py
Labels: bug, enhancement

#55 List Operation
  service/models.py
  service/service.py
Labels: enhancement

#57 Added functions for delete operation
  service/models.py
Labels: enhancement

#59 Added function - Query supplier(s) by its name
  service/models.py
Labels: enhancement

#61 Add the find function that is the read operation
  service/models.py
  service/service.py
Labels: enhancement

#58 Creates a route for Update Operation.
  service/service.py
Labels: enhancement

#62 Create route for action operation
  service/service.py
Labels: enhancement

#60 Add test cases for list operation
  .coverage
  .gitignore
  service/__pycache__/__init__.cpython-36.pyc
  service/__pycache__/models.cpython-36.pyc
  service/__pycache__/service.cpython-36.pyc
  tests/test_service.py
  tests/test_suppliers.py
Labels: enhancement

#65 Bugs in service tests for create_suppliers()
  service/models.py
  service/service.py
  tests/suppliers_factory.py
  tests/test_service.py
  tests/test_suppliers.py
Labels: bug

#66 Added update operation, fixed bug for update router
  service/models.py
  service/service.py
Labels: bug, enhancement

#67 Add delete route
  service/service.py
Labels: enhancement

#68 Writes model tests and service tests for Update.
  service/service.py
  tests/suppliers_factory.py
  tests/test_service.py
  tests/test_suppliers.py
Labels: enhancement

#72 Writes models test and service test for DELETE.
  tests/test_service.py
  tests/test_suppliers.py
Labels: testing

#70 Create an action operation
  service/models.py
  service/service.py
Labels: enhancement

#76 Error raised in Update Tests
  service/service.py
  tests/test_service.py
  tests/test_suppliers.py
Labels: bug

#74 create query operation router
  service/service.py
Labels: enhancement

#71 Add Read test case and Update read route
  service/models.py
  service/service.py
  tests/test_service.py
Labels: enhancement, testing

#78 Create test cases for query operation
  tests/test_service.py
  tests/test_suppliers.py
Labels: testing

#77 Added id and not-found validation for multiple operations
  service/models.py
  service/service.py
Labels: bug

#79 Create Test Cases for Action Operation
  tests/test_service.py
Labels: testing

#83 Coverage improvement in model.py
  service/models.py
  tests/test_service.py
  tests/test_suppliers.py
Labels: testing

#89 Handle empty Content-Type and typo fix
  service/service.py
Labels: bug

#90 Update test_service.py
  tests/test_service.py
Labels: testing

#88 Update readme
  README.md
Labels: documentation

#91 Add tests of service
  service/service.py
  tests/suppliers_factory.py
  tests/test_service.py
Labels: testing

#93 Fix error raised in Create Op
  service/service.py
Labels: bug
