Repository nyu-devops-fall19-suppliers/suppliers, pull requests merged in 2019-12, with the labels that each got.

#163 Refactor Restful Plus READ Operation
  requirements.txt
  service/__init__.py
  service/service.py
  tests/test_service.py
Labels: enhancement

#162 Refactor service.py with Authorization Decorator and Swagger Configuration
  requirements.txt
  service/__init__.py
  service/service.py
Labels: enhancement

#169 Refactor Action Operation
  service/service.py
Labels: enhancement

#166 Refactor Delete Operation
  service/service.py
Labels: enhancement

#173 Authorizations Checker & Fix Update Display Error
  service/__init__.py
  service/service.py
  tests/test_service.py
Labels: enhancement

#177 Update manifest.yml to support CI prod-deploy stage
  manifest.yml
Labels: bug, enhancement, technical debt

#178 Remove Token Checker
  service/__init__.py
  service/service.py
  tests/test_service.py
Labels: bug

#182 Fix BDD Bug
  features/steps/supplier_steps.py
  features/suppliers.feature
  service/__init__.py
  service/service.py
  service/static/js/rest_api.js
  tests/test_service.py
Labels: bug

#183 Add apidoc access point to UI page
  service/static/index.html
  service/static/js/rest_api.js
Labels: enhancement
